server:
  port: 7002

eureka:
  instance:
    hostname: localhost7002 #Eureka服务端的实例名称
  client:
    register-with-eureka: false #是否注册自身
    fetch-registry: false #false表示该服务为注册中心
    service-url: #监控页面的地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7003/eureka/